server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "demo.local"
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/opt/spire/data/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "memory" {
        plugin_data = {}
    }
}
