server {
    bind_address = "127.0.0.1"
    bind_port = "8081"
    trust_domain = "demo.local"
    data_dir = "/opt/spire/data/server"
    log_level = "DEBUG"
    socket_path = "/tmp/spire-server/private/api.sock"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/opt/spire/data/server/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "memory" {
        plugin_data = {}
    }
}
