agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/opt/spire/sockets/workload_api.sock"
    trust_domain = "demo.local"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "memory" {
        plugin_data {
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {
            # In a Dockerized test env, discovering UID/GID of the caller is enough
            discover_workload_path = true
        }
    }
}
